// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: spec.proto

package spec

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN       MessageType = 0
	MessageType_REPLY         MessageType = 1
	MessageType_REQUEST       MessageType = 2
	MessageType_POLL          MessageType = 3
	MessageType_BROADCAST     MessageType = 4
	MessageType_ERROR         MessageType = 5
	MessageType_TIMEOUT       MessageType = 6
	MessageType_PING          MessageType = 7
	MessageType_PONG          MessageType = 8
	MessageType_I_AM_PRODUCER MessageType = 9
	MessageType_I_AM_CONSUMER MessageType = 10
	MessageType_EMPTY         MessageType = 12
)

var MessageType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "REPLY",
	2:  "REQUEST",
	3:  "POLL",
	4:  "BROADCAST",
	5:  "ERROR",
	6:  "TIMEOUT",
	7:  "PING",
	8:  "PONG",
	9:  "I_AM_PRODUCER",
	10: "I_AM_CONSUMER",
	12: "EMPTY",
}

var MessageType_value = map[string]int32{
	"UNKNOWN":       0,
	"REPLY":         1,
	"REQUEST":       2,
	"POLL":          3,
	"BROADCAST":     4,
	"ERROR":         5,
	"TIMEOUT":       6,
	"PING":          7,
	"PONG":          8,
	"I_AM_PRODUCER": 9,
	"I_AM_CONSUMER": 10,
	"EMPTY":         12,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{0}
}

type Message struct {
	Topic     string      `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	RequestID uint64      `protobuf:"varint,2,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Data      []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Type      MessageType `protobuf:"varint,4,opt,name=type,proto3,enum=spec.MessageType" json:"type,omitempty"`
	Ttl       uint32      `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	TimeoutMs uint32      `protobuf:"varint,6,opt,name=timeoutMs,proto3" json:"timeoutMs,omitempty"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Message) GetRequestID() uint64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN
}

func (m *Message) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *Message) GetTimeoutMs() uint32 {
	if m != nil {
		return m.TimeoutMs
	}
	return 0
}

func init() {
	proto.RegisterEnum("spec.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Message)(nil), "spec.Message")
}

func init() { proto.RegisterFile("spec.proto", fileDescriptor_423806180556987f) }

var fileDescriptor_423806180556987f = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x6a, 0xea, 0x40,
	0x14, 0xc6, 0x33, 0x9a, 0xa8, 0x39, 0xea, 0x65, 0x1c, 0xee, 0x62, 0x16, 0x97, 0x10, 0x2e, 0x5c,
	0x08, 0x77, 0xe1, 0xa2, 0x7d, 0x02, 0xff, 0x0c, 0x12, 0x6a, 0x32, 0xe9, 0x31, 0xa1, 0xb8, 0x12,
	0x6b, 0x87, 0x22, 0xb4, 0x24, 0x35, 0xe3, 0xc2, 0xb7, 0xe8, 0x63, 0xf8, 0x28, 0x5d, 0xba, 0xec,
	0xb2, 0xe8, 0x8b, 0x94, 0x8c, 0xa5, 0x76, 0xf7, 0xcd, 0x6f, 0xf8, 0x7d, 0x1f, 0x1c, 0x80, 0xb2,
	0x50, 0xab, 0x7e, 0xb1, 0xc9, 0x75, 0xce, 0xec, 0x2a, 0xff, 0xdd, 0x13, 0x68, 0x46, 0xaa, 0x2c,
	0x97, 0x8f, 0x8a, 0xfd, 0x06, 0x47, 0xe7, 0xc5, 0x7a, 0xc5, 0x89, 0x4f, 0x02, 0x17, 0xcf, 0x0f,
	0xf6, 0x07, 0xdc, 0x8d, 0x7a, 0xd9, 0xaa, 0x52, 0x87, 0x63, 0x5e, 0xf3, 0x49, 0x60, 0xe3, 0x05,
	0x30, 0x06, 0xf6, 0xc3, 0x52, 0x2f, 0x79, 0xdd, 0x27, 0x41, 0x07, 0x4d, 0x66, 0xff, 0xc0, 0xd6,
	0xbb, 0x42, 0x71, 0xdb, 0x27, 0xc1, 0xaf, 0xab, 0x5e, 0xdf, 0x8c, 0x7e, 0x8d, 0xa4, 0xbb, 0x42,
	0xa1, 0xf9, 0x66, 0x14, 0xea, 0x5a, 0x3f, 0x71, 0xc7, 0x27, 0x41, 0x17, 0xab, 0x58, 0x4d, 0xe9,
	0xf5, 0xb3, 0xca, 0xb7, 0x3a, 0x2a, 0x79, 0xc3, 0xf0, 0x0b, 0xf8, 0xbf, 0x27, 0xd0, 0xfe, 0xd1,
	0xc2, 0xda, 0xd0, 0xcc, 0xe2, 0x9b, 0x58, 0xde, 0xc5, 0xd4, 0x62, 0x2e, 0x38, 0x28, 0x92, 0xe9,
	0x9c, 0x92, 0x8a, 0xa3, 0xb8, 0xcd, 0xc4, 0x2c, 0xa5, 0x35, 0xd6, 0x02, 0x3b, 0x91, 0xd3, 0x29,
	0xad, 0xb3, 0x2e, 0xb8, 0x43, 0x94, 0x83, 0xf1, 0x68, 0x30, 0x4b, 0xa9, 0x5d, 0x09, 0x02, 0x51,
	0x22, 0x75, 0x2a, 0x21, 0x0d, 0x23, 0x21, 0xb3, 0x94, 0x36, 0x8c, 0x10, 0xc6, 0x13, 0xda, 0x3c,
	0xab, 0xf1, 0x84, 0xb6, 0x58, 0x0f, 0xba, 0xe1, 0x62, 0x10, 0x2d, 0x12, 0x94, 0xe3, 0x6c, 0x24,
	0x90, 0xba, 0xdf, 0x68, 0x24, 0xe3, 0x59, 0x16, 0x09, 0xa4, 0x60, 0x1a, 0xa3, 0x24, 0x9d, 0xd3,
	0xce, 0x90, 0xbf, 0x1d, 0x3d, 0x72, 0x38, 0x7a, 0xe4, 0xe3, 0xe8, 0x91, 0xd7, 0x93, 0x67, 0x1d,
	0x4e, 0x9e, 0xf5, 0x7e, 0xf2, 0xac, 0xfb, 0x86, 0x39, 0xfe, 0xf5, 0x67, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x11, 0x33, 0xc1, 0x30, 0x8a, 0x01, 0x00, 0x00,
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Topic) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSpec(dAtA, i, uint64(len(m.Topic)))
		i += copy(dAtA[i:], m.Topic)
	}
	if m.RequestID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSpec(dAtA, i, uint64(m.RequestID))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintSpec(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if m.Type != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintSpec(dAtA, i, uint64(m.Type))
	}
	if m.Ttl != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintSpec(dAtA, i, uint64(m.Ttl))
	}
	if m.TimeoutMs != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintSpec(dAtA, i, uint64(m.TimeoutMs))
	}
	return i, nil
}

func encodeVarintSpec(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Topic)
	if l > 0 {
		n += 1 + l + sovSpec(uint64(l))
	}
	if m.RequestID != 0 {
		n += 1 + sovSpec(uint64(m.RequestID))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovSpec(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovSpec(uint64(m.Type))
	}
	if m.Ttl != 0 {
		n += 1 + sovSpec(uint64(m.Ttl))
	}
	if m.TimeoutMs != 0 {
		n += 1 + sovSpec(uint64(m.TimeoutMs))
	}
	return n
}

func sovSpec(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSpec(x uint64) (n int) {
	return sovSpec(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpec
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpec
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Topic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestID", wireType)
			}
			m.RequestID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSpec
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (MessageType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ttl", wireType)
			}
			m.Ttl = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ttl |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutMs", wireType)
			}
			m.TimeoutMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutMs |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpec(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSpec
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSpec(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSpec
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSpec
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSpec
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSpec(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSpec = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSpec   = fmt.Errorf("proto: integer overflow")
)
